spring:
  application:
    name: flow.ci
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      location: ${java.io.tmpdir}
  config:
    import:
      - classpath:application-management.yaml
      - classpath:application-db.yaml

server:
  port: ${FLOWCI_SERVER_PORT:8080}
  address: ${FLOWCI_SERVER_ADDRESS:0.0.0.0}
  error:
    whitelabel:
      enabled: false
    path: /error