## Docker-Compose file is used to start dependent services

version: '3'
services:
  db-1:
    image: mongo:6
    restart: always
    container_name: flowci-debug-db-1
    ports:
      - "27017:27017"
    entrypoint: [
      "/usr/bin/mongod",
      "--port", "27017",
      "--replSet", "rs0",
      "--bind_ip_all",
    ]

  db-init:
    image: mongo:6
    container_name: flowci-debug-db-init
    volumes:
      - ./script:/ws
    entrypoint: "/ws/mongo_init.sh"

  zk:
    image: zookeeper:3.6
    container_name: flowci-debug-zk
    restart: always
    ports:
      - "2181:2181"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowci-debug-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-02T10-51-33Z
    container_name: flowci-debug-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9090:9090"
    command: "server /data --console-address \":9090\""